process.exit(0)
    .catch((error) => {
        console.log(error);
    });